global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: /metrics

  - job_name: 'storage-metadata'
    static_configs:
      - targets: ['storage-metadata:9091']
    metrics_path: /metrics

  - job_name: 'storage-node'
    static_configs:
      - targets: ['storage-node:9092']
    metrics_path: /metrics

  - job_name: 'replication-service'
    static_configs:
      - targets: ['replication-service:9093']
    metrics_path: /metrics
