// Generated protobuf code
// This is generated by tonic-build during the build process (Cargo)
// or via rust_prost_library (Bazel)

// When building with Cargo, include the generated code from build.rs
#[cfg(not(bazel))]
pub mod storage_metadata {
    include!(concat!(env!("OUT_DIR"), "/storage_metadata.rs"));
}

#[cfg(not(bazel))]
pub mod storage_node {
    include!(concat!(env!("OUT_DIR"), "/storage_node.rs"));
}

// When building with Bazel, re-export from the prost-generated crates
// The crate names are derived from the proto_library target names
#[cfg(bazel)]
pub use storage_metadata_proto::storage_metadata;

#[cfg(bazel)]
pub use storage_node_proto::storage_node;

// Client trait abstractions for dependency injection and testing
pub mod clients;
pub use clients::{MetadataClient, StorageNodeClient, StorageNodeClientFactory};
